version: '3.8'

services:
  django:
    build: .
    command: sh -c "sleep 5 && python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=django-insecure-$h-t!fd&)x_sx&o-@&^x!44ru!n1em%_wpj^#o1j1!n8u-h5p8
      - DEBUG=True
      - ALLOWED_HOSTS=*
      - DB_ENGINE=django.db.backends.postgresql_psycopg2
      - DB_NAME=technical_db
      - DB_USER=technical_user
      - DB_PASSWORD=technical_root
      - DB_PORT=5432
      - DB_HOST=127.0.0.1

      - CACHE=redis

    depends_on:
      - postgres_db
      - redis
  postgres_db:
    image: postgres:alpine3.17
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=technical_user
      - POSTGRES_DB=technical_db
      - POSTGRES_PASSWORD=technical_db
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: "redis:alpine"
    hostname: redis
    ports:
      - "6379:6379"

volumes:
  pgdata: