# Generated by Django 4.2.1 on 2023-05-19 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_sponsor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('BACHELOR', 'Bachelor'), ('MAGISTER', 'Magister')], default='BACHELOR', max_length=10)),
                ('university', models.CharField(help_text='Student University name', max_length=255)),
                ('contract', models.BigIntegerField(blank=True, default=0, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Students',
                'ordering': ['-user__date_joined'],
            },
        ),
    ]
