# Generated by Django 4.2.1 on 2023-05-21 11:27

import apps.geo
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.JSONField(default=apps.geo.default_name)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=255, null=True, unique=True)),
                ('ordering', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name_plural': 'Districts',
                'ordering': ['ordering'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.JSONField(default=apps.geo.default_name)),
                ('slug', models.SlugField(allow_unicode=True, max_length=255, null=True, unique=True)),
                ('ordering', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name_plural': 'Regions',
                'ordering': ['ordering'],
            },
        ),
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.JSONField(default=apps.geo.default_name)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=255, null=True, unique=True)),
                ('ordering', models.IntegerField(default=1)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='village_district', to='geo.district')),
            ],
            options={
                'verbose_name_plural': 'Villages',
                'ordering': ['ordering'],
            },
        ),
        migrations.AddField(
            model_name='district',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='district_region', to='geo.region'),
        ),
    ]
